Class {
	#name : #GlutinEventVirtualKeyCode,
	#superclass : #GlutinEnum,
	#classVars : [
		'A',
		'AbntC1',
		'AbntC2',
		'Add',
		'Apostrophe',
		'Apps',
		'At',
		'Ax',
		'B',
		'Back',
		'Backslash',
		'C',
		'Calculator',
		'Capital',
		'Caret',
		'Colon',
		'Comma',
		'Compose',
		'Convert',
		'Copy',
		'Cut',
		'D',
		'Decimal',
		'Delete',
		'Divide',
		'Down',
		'E',
		'End',
		'Equals',
		'Escape',
		'F',
		'F1',
		'F10',
		'F11',
		'F12',
		'F13',
		'F14',
		'F15',
		'F16',
		'F17',
		'F18',
		'F19',
		'F2',
		'F20',
		'F21',
		'F22',
		'F23',
		'F24',
		'F3',
		'F4',
		'F5',
		'F6',
		'F7',
		'F8',
		'F9',
		'G',
		'Grave',
		'H',
		'Home',
		'I',
		'Insert',
		'J',
		'K',
		'Kana',
		'Kanji',
		'Key0',
		'Key1',
		'Key2',
		'Key3',
		'Key4',
		'Key5',
		'Key6',
		'Key7',
		'Key8',
		'Key9',
		'L',
		'LAlt',
		'LBracket',
		'LControl',
		'LShift',
		'LWin',
		'Left',
		'M',
		'Mail',
		'MediaSelect',
		'MediaStop',
		'Minus',
		'Multiply',
		'Mute',
		'MyComputer',
		'N',
		'NavigateBackward',
		'NavigateForward',
		'NextTrack',
		'NoConvert',
		'Numlock',
		'Numpad0',
		'Numpad1',
		'Numpad2',
		'Numpad3',
		'Numpad4',
		'Numpad5',
		'Numpad6',
		'Numpad7',
		'Numpad8',
		'Numpad9',
		'NumpadComma',
		'NumpadEnter',
		'NumpadEquals',
		'O',
		'OEM102',
		'P',
		'PageDown',
		'PageUp',
		'Paste',
		'Pause',
		'Period',
		'PlayPause',
		'Power',
		'PrevTrack',
		'Q',
		'R',
		'RAlt',
		'RBracket',
		'RControl',
		'RShift',
		'RWin',
		'Return',
		'Right',
		'S',
		'Scroll',
		'Semicolon',
		'Slash',
		'Sleep',
		'Snapshot',
		'Space',
		'Stop',
		'Subtract',
		'Sysrq',
		'T',
		'Tab',
		'U',
		'Underline',
		'Unlabeled',
		'Up',
		'V',
		'VolumeDown',
		'VolumeUp',
		'W',
		'Wake',
		'WebBack',
		'WebFavorites',
		'WebForward',
		'WebHome',
		'WebRefresh',
		'WebSearch',
		'WebStop',
		'X',
		'Y',
		'Yen',
		'Z'
	],
	#category : #'Glutin-Enums'
}

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> A [
	"This method was automatically generated"
	^ A
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> AbntC1 [
	"This method was automatically generated"
	^ AbntC1
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> AbntC2 [
	"This method was automatically generated"
	^ AbntC2
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Add [
	"This method was automatically generated"
	^ Add
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Apostrophe [
	"This method was automatically generated"
	^ Apostrophe
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Apps [
	"This method was automatically generated"
	^ Apps
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> At [
	"This method was automatically generated"
	^ At
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Ax [
	"This method was automatically generated"
	^ Ax
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> B [
	"This method was automatically generated"
	^ B
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Back [
	"This method was automatically generated"
	^ Back
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Backslash [
	"This method was automatically generated"
	^ Backslash
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> C [
	"This method was automatically generated"
	^ C
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Calculator [
	"This method was automatically generated"
	^ Calculator
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Capital [
	"This method was automatically generated"
	^ Capital
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Caret [
	"This method was automatically generated"
	^ Caret
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Colon [
	"This method was automatically generated"
	^ Colon
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Comma [
	"This method was automatically generated"
	^ Comma
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Compose [
	"This method was automatically generated"
	^ Compose
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Convert [
	"This method was automatically generated"
	^ Convert
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Copy [
	"This method was automatically generated"
	^ Copy
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Cut [
	"This method was automatically generated"
	^ Cut
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> D [
	"This method was automatically generated"
	^ D
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Decimal [
	"This method was automatically generated"
	^ Decimal
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Delete [
	"This method was automatically generated"
	^ Delete
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Divide [
	"This method was automatically generated"
	^ Divide
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Down [
	"This method was automatically generated"
	^ Down
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> E [
	"This method was automatically generated"
	^ E
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> End [
	"This method was automatically generated"
	^ End
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Equals [
	"This method was automatically generated"
	^ Equals
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Escape [
	"This method was automatically generated"
	^ Escape
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F [
	"This method was automatically generated"
	^ F
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F1 [
	"This method was automatically generated"
	^ F1
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F10 [
	"This method was automatically generated"
	^ F10
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F11 [
	"This method was automatically generated"
	^ F11
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F12 [
	"This method was automatically generated"
	^ F12
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F13 [
	"This method was automatically generated"
	^ F13
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F14 [
	"This method was automatically generated"
	^ F14
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F15 [
	"This method was automatically generated"
	^ F15
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F16 [
	"This method was automatically generated"
	^ F16
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F17 [
	"This method was automatically generated"
	^ F17
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F18 [
	"This method was automatically generated"
	^ F18
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F19 [
	"This method was automatically generated"
	^ F19
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F2 [
	"This method was automatically generated"
	^ F2
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F20 [
	"This method was automatically generated"
	^ F20
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F21 [
	"This method was automatically generated"
	^ F21
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F22 [
	"This method was automatically generated"
	^ F22
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F23 [
	"This method was automatically generated"
	^ F23
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F24 [
	"This method was automatically generated"
	^ F24
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F3 [
	"This method was automatically generated"
	^ F3
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F4 [
	"This method was automatically generated"
	^ F4
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F5 [
	"This method was automatically generated"
	^ F5
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F6 [
	"This method was automatically generated"
	^ F6
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F7 [
	"This method was automatically generated"
	^ F7
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F8 [
	"This method was automatically generated"
	^ F8
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> F9 [
	"This method was automatically generated"
	^ F9
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> G [
	"This method was automatically generated"
	^ G
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Grave [
	"This method was automatically generated"
	^ Grave
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> H [
	"This method was automatically generated"
	^ H
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Home [
	"This method was automatically generated"
	^ Home
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> I [
	"This method was automatically generated"
	^ I
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Insert [
	"This method was automatically generated"
	^ Insert
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> J [
	"This method was automatically generated"
	^ J
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> K [
	"This method was automatically generated"
	^ K
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Kana [
	"This method was automatically generated"
	^ Kana
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Kanji [
	"This method was automatically generated"
	^ Kanji
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key0 [
	"This method was automatically generated"
	^ Key0
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key1 [
	"This method was automatically generated"
	^ Key1
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key2 [
	"This method was automatically generated"
	^ Key2
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key3 [
	"This method was automatically generated"
	^ Key3
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key4 [
	"This method was automatically generated"
	^ Key4
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key5 [
	"This method was automatically generated"
	^ Key5
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key6 [
	"This method was automatically generated"
	^ Key6
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key7 [
	"This method was automatically generated"
	^ Key7
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key8 [
	"This method was automatically generated"
	^ Key8
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Key9 [
	"This method was automatically generated"
	^ Key9
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> L [
	"This method was automatically generated"
	^ L
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> LAlt [
	"This method was automatically generated"
	^ LAlt
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> LBracket [
	"This method was automatically generated"
	^ LBracket
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> LControl [
	"This method was automatically generated"
	^ LControl
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> LShift [
	"This method was automatically generated"
	^ LShift
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> LWin [
	"This method was automatically generated"
	^ LWin
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Left [
	"This method was automatically generated"
	^ Left
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> M [
	"This method was automatically generated"
	^ M
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Mail [
	"This method was automatically generated"
	^ Mail
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> MediaSelect [
	"This method was automatically generated"
	^ MediaSelect
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> MediaStop [
	"This method was automatically generated"
	^ MediaStop
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Minus [
	"This method was automatically generated"
	^ Minus
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Multiply [
	"This method was automatically generated"
	^ Multiply
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Mute [
	"This method was automatically generated"
	^ Mute
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> MyComputer [
	"This method was automatically generated"
	^ MyComputer
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> N [
	"This method was automatically generated"
	^ N
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NavigateBackward [
	"This method was automatically generated"
	^ NavigateBackward
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NavigateForward [
	"This method was automatically generated"
	^ NavigateForward
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NextTrack [
	"This method was automatically generated"
	^ NextTrack
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NoConvert [
	"This method was automatically generated"
	^ NoConvert
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numlock [
	"This method was automatically generated"
	^ Numlock
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad0 [
	"This method was automatically generated"
	^ Numpad0
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad1 [
	"This method was automatically generated"
	^ Numpad1
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad2 [
	"This method was automatically generated"
	^ Numpad2
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad3 [
	"This method was automatically generated"
	^ Numpad3
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad4 [
	"This method was automatically generated"
	^ Numpad4
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad5 [
	"This method was automatically generated"
	^ Numpad5
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad6 [
	"This method was automatically generated"
	^ Numpad6
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad7 [
	"This method was automatically generated"
	^ Numpad7
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad8 [
	"This method was automatically generated"
	^ Numpad8
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Numpad9 [
	"This method was automatically generated"
	^ Numpad9
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NumpadComma [
	"This method was automatically generated"
	^ NumpadComma
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NumpadEnter [
	"This method was automatically generated"
	^ NumpadEnter
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> NumpadEquals [
	"This method was automatically generated"
	^ NumpadEquals
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> O [
	"This method was automatically generated"
	^ O
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> OEM102 [
	"This method was automatically generated"
	^ OEM102
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> P [
	"This method was automatically generated"
	^ P
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> PageDown [
	"This method was automatically generated"
	^ PageDown
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> PageUp [
	"This method was automatically generated"
	^ PageUp
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Paste [
	"This method was automatically generated"
	^ Paste
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Pause [
	"This method was automatically generated"
	^ Pause
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Period [
	"This method was automatically generated"
	^ Period
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> PlayPause [
	"This method was automatically generated"
	^ PlayPause
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Power [
	"This method was automatically generated"
	^ Power
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> PrevTrack [
	"This method was automatically generated"
	^ PrevTrack
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Q [
	"This method was automatically generated"
	^ Q
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> R [
	"This method was automatically generated"
	^ R
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> RAlt [
	"This method was automatically generated"
	^ RAlt
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> RBracket [
	"This method was automatically generated"
	^ RBracket
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> RControl [
	"This method was automatically generated"
	^ RControl
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> RShift [
	"This method was automatically generated"
	^ RShift
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> RWin [
	"This method was automatically generated"
	^ RWin
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Return [
	"This method was automatically generated"
	^ Return
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Right [
	"This method was automatically generated"
	^ Right
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> S [
	"This method was automatically generated"
	^ S
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Scroll [
	"This method was automatically generated"
	^ Scroll
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Semicolon [
	"This method was automatically generated"
	^ Semicolon
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Slash [
	"This method was automatically generated"
	^ Slash
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Sleep [
	"This method was automatically generated"
	^ Sleep
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Snapshot [
	"This method was automatically generated"
	^ Snapshot
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Space [
	"This method was automatically generated"
	^ Space
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Stop [
	"This method was automatically generated"
	^ Stop
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Subtract [
	"This method was automatically generated"
	^ Subtract
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Sysrq [
	"This method was automatically generated"
	^ Sysrq
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> T [
	"This method was automatically generated"
	^ T
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Tab [
	"This method was automatically generated"
	^ Tab
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> U [
	"This method was automatically generated"
	^ U
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Underline [
	"This method was automatically generated"
	^ Underline
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Unlabeled [
	"This method was automatically generated"
	^ Unlabeled
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Up [
	"This method was automatically generated"
	^ Up
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> V [
	"This method was automatically generated"
	^ V
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> VolumeDown [
	"This method was automatically generated"
	^ VolumeDown
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> VolumeUp [
	"This method was automatically generated"
	^ VolumeUp
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> W [
	"This method was automatically generated"
	^ W
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Wake [
	"This method was automatically generated"
	^ Wake
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebBack [
	"This method was automatically generated"
	^ WebBack
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebFavorites [
	"This method was automatically generated"
	^ WebFavorites
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebForward [
	"This method was automatically generated"
	^ WebForward
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebHome [
	"This method was automatically generated"
	^ WebHome
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebRefresh [
	"This method was automatically generated"
	^ WebRefresh
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebSearch [
	"This method was automatically generated"
	^ WebSearch
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> WebStop [
	"This method was automatically generated"
	^ WebStop
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> X [
	"This method was automatically generated"
	^ X
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Y [
	"This method was automatically generated"
	^ Y
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Yen [
	"This method was automatically generated"
	^ Yen
]

{ #category : #'accessing enum' }
GlutinEventVirtualKeyCode class >> Z [
	"This method was automatically generated"
	^ Z
]

{ #category : #'enum declaration' }
GlutinEventVirtualKeyCode class >> externalDeclaration [
	"
	self rebuildEnumAccessors
	"

	^ #(
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    Snapshot,
    Scroll,
    Pause,

    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    Back,
    Return,
    Space,

    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,

    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
	)
]

{ #category : #'enum declaration' }
GlutinEventVirtualKeyCode class >> externalType [
	^ FFIUInt32 new
]

{ #category : #'class initialization' }
GlutinEventVirtualKeyCode class >> initialize [
	super initialize
]
