Trait {
	#name : #TGlutinCommonEventVisitor,
	#category : #'Glutin-Events'
}

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitLoopDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitMainEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitNewEvents: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitRedrawEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitResumed: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitSuspended: anEvent [
]

{ #category : #'event - visiting' }
TGlutinCommonEventVisitor >> visitUserEvent: anEvent [
]
