Trait {
	#name : #TGlutinEventVisitor,
	#category : #'Glutin-Events'
}

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitCharacterReceivedEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitCursorMovedEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitKeyboardInputEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitLoopDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitModifiersChanged: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitMouseInputEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitMouseWheelEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitNewEvents: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitResumed: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitSuspended: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitTouchEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitUnknownEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowCloseRequest: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowFocusedEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowMovedEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowRedrawRequested: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowResizedEvent: anEvent [
]

{ #category : #'event - visiting' }
TGlutinEventVisitor >> visitWindowScaleFactorChangedEvent: anEvent [
]
