Trait {
	#name : #TGlutinEventVisitor,
	#category : #'Glutin-Events'
}

{ #category : #visiting }
TGlutinEventVisitor >> visitCharacterReceivedEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitCursorMovedEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitKeyboardInputEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitMouseInputEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitMouseWheelEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitTouchEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowCloseRequest: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowDestroyed: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowFocusedEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowMovedEvent: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowRedrawRequested: anEvent [
]

{ #category : #visiting }
TGlutinEventVisitor >> visitWindowResizedEvent: anEvent [
]
