Class {
	#name : #WinitEventVirtualKeyCode,
	#superclass : #WinitEnum,
	#classVars : [
		'A',
		'AbntC1',
		'AbntC2',
		'Add',
		'Apostrophe',
		'Apps',
		'Asterisk',
		'At',
		'Ax',
		'B',
		'Back',
		'Backslash',
		'C',
		'Calculator',
		'Capital',
		'Caret',
		'Colon',
		'Comma',
		'Compose',
		'Convert',
		'Copy',
		'Cut',
		'D',
		'Decimal',
		'Delete',
		'Divide',
		'Down',
		'E',
		'End',
		'Equals',
		'Escape',
		'F',
		'F1',
		'F10',
		'F11',
		'F12',
		'F13',
		'F14',
		'F15',
		'F16',
		'F17',
		'F18',
		'F19',
		'F2',
		'F20',
		'F21',
		'F22',
		'F23',
		'F24',
		'F3',
		'F4',
		'F5',
		'F6',
		'F7',
		'F8',
		'F9',
		'G',
		'Grave',
		'H',
		'Home',
		'I',
		'Insert',
		'J',
		'K',
		'Kana',
		'Kanji',
		'Key0',
		'Key1',
		'Key2',
		'Key3',
		'Key4',
		'Key5',
		'Key6',
		'Key7',
		'Key8',
		'Key9',
		'L',
		'LAlt',
		'LBracket',
		'LControl',
		'LShift',
		'LWin',
		'Left',
		'M',
		'Mail',
		'MediaSelect',
		'MediaStop',
		'Minus',
		'Multiply',
		'Mute',
		'MyComputer',
		'N',
		'NavigateBackward',
		'NavigateForward',
		'NextTrack',
		'NoConvert',
		'Numlock',
		'Numpad0',
		'Numpad1',
		'Numpad2',
		'Numpad3',
		'Numpad4',
		'Numpad5',
		'Numpad6',
		'Numpad7',
		'Numpad8',
		'Numpad9',
		'NumpadAdd',
		'NumpadComma',
		'NumpadDecimal',
		'NumpadDivide',
		'NumpadEnter',
		'NumpadEquals',
		'NumpadMultiply',
		'NumpadSubtract',
		'O',
		'OEM102',
		'P',
		'PageDown',
		'PageUp',
		'Paste',
		'Pause',
		'Period',
		'PlayPause',
		'Plus',
		'Power',
		'PrevTrack',
		'Q',
		'R',
		'RAlt',
		'RBracket',
		'RControl',
		'RShift',
		'RWin',
		'Return',
		'Right',
		'S',
		'Scroll',
		'Semicolon',
		'Slash',
		'Sleep',
		'Snapshot',
		'Space',
		'Stop',
		'Subtract',
		'Sysrq',
		'T',
		'Tab',
		'U',
		'Underline',
		'Unlabeled',
		'Up',
		'V',
		'VolumeDown',
		'VolumeUp',
		'W',
		'Wake',
		'WebBack',
		'WebFavorites',
		'WebForward',
		'WebHome',
		'WebRefresh',
		'WebSearch',
		'WebStop',
		'X',
		'Y',
		'Yen',
		'Z'
	],
	#category : #'Glutin-Enums'
}

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> A [
	"This method was automatically generated"
	^ A
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> AbntC1 [
	"This method was automatically generated"
	^ AbntC1
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> AbntC2 [
	"This method was automatically generated"
	^ AbntC2
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Add [
	"This method was automatically generated"
	^ Add
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Apostrophe [
	"This method was automatically generated"
	^ Apostrophe
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Apps [
	"This method was automatically generated"
	^ Apps
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Asterisk [
	"This method was automatically generated"
	^ Asterisk
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> At [
	"This method was automatically generated"
	^ At
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Ax [
	"This method was automatically generated"
	^ Ax
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> B [
	"This method was automatically generated"
	^ B
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Back [
	"This method was automatically generated"
	^ Back
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Backslash [
	"This method was automatically generated"
	^ Backslash
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> C [
	"This method was automatically generated"
	^ C
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Calculator [
	"This method was automatically generated"
	^ Calculator
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Capital [
	"This method was automatically generated"
	^ Capital
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Caret [
	"This method was automatically generated"
	^ Caret
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Colon [
	"This method was automatically generated"
	^ Colon
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Comma [
	"This method was automatically generated"
	^ Comma
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Compose [
	"This method was automatically generated"
	^ Compose
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Convert [
	"This method was automatically generated"
	^ Convert
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Copy [
	"This method was automatically generated"
	^ Copy
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Cut [
	"This method was automatically generated"
	^ Cut
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> D [
	"This method was automatically generated"
	^ D
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Decimal [
	"This method was automatically generated"
	^ Decimal
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Delete [
	"This method was automatically generated"
	^ Delete
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Divide [
	"This method was automatically generated"
	^ Divide
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Down [
	"This method was automatically generated"
	^ Down
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> E [
	"This method was automatically generated"
	^ E
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> End [
	"This method was automatically generated"
	^ End
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Equals [
	"This method was automatically generated"
	^ Equals
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Escape [
	"This method was automatically generated"
	^ Escape
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F [
	"This method was automatically generated"
	^ F
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F1 [
	"This method was automatically generated"
	^ F1
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F10 [
	"This method was automatically generated"
	^ F10
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F11 [
	"This method was automatically generated"
	^ F11
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F12 [
	"This method was automatically generated"
	^ F12
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F13 [
	"This method was automatically generated"
	^ F13
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F14 [
	"This method was automatically generated"
	^ F14
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F15 [
	"This method was automatically generated"
	^ F15
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F16 [
	"This method was automatically generated"
	^ F16
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F17 [
	"This method was automatically generated"
	^ F17
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F18 [
	"This method was automatically generated"
	^ F18
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F19 [
	"This method was automatically generated"
	^ F19
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F2 [
	"This method was automatically generated"
	^ F2
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F20 [
	"This method was automatically generated"
	^ F20
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F21 [
	"This method was automatically generated"
	^ F21
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F22 [
	"This method was automatically generated"
	^ F22
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F23 [
	"This method was automatically generated"
	^ F23
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F24 [
	"This method was automatically generated"
	^ F24
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F3 [
	"This method was automatically generated"
	^ F3
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F4 [
	"This method was automatically generated"
	^ F4
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F5 [
	"This method was automatically generated"
	^ F5
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F6 [
	"This method was automatically generated"
	^ F6
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F7 [
	"This method was automatically generated"
	^ F7
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F8 [
	"This method was automatically generated"
	^ F8
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> F9 [
	"This method was automatically generated"
	^ F9
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> G [
	"This method was automatically generated"
	^ G
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Grave [
	"This method was automatically generated"
	^ Grave
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> H [
	"This method was automatically generated"
	^ H
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Home [
	"This method was automatically generated"
	^ Home
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> I [
	"This method was automatically generated"
	^ I
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Insert [
	"This method was automatically generated"
	^ Insert
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> J [
	"This method was automatically generated"
	^ J
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> K [
	"This method was automatically generated"
	^ K
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Kana [
	"This method was automatically generated"
	^ Kana
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Kanji [
	"This method was automatically generated"
	^ Kanji
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key0 [
	"This method was automatically generated"
	^ Key0
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key1 [
	"This method was automatically generated"
	^ Key1
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key2 [
	"This method was automatically generated"
	^ Key2
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key3 [
	"This method was automatically generated"
	^ Key3
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key4 [
	"This method was automatically generated"
	^ Key4
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key5 [
	"This method was automatically generated"
	^ Key5
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key6 [
	"This method was automatically generated"
	^ Key6
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key7 [
	"This method was automatically generated"
	^ Key7
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key8 [
	"This method was automatically generated"
	^ Key8
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Key9 [
	"This method was automatically generated"
	^ Key9
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> L [
	"This method was automatically generated"
	^ L
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> LAlt [
	"This method was automatically generated"
	^ LAlt
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> LBracket [
	"This method was automatically generated"
	^ LBracket
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> LControl [
	"This method was automatically generated"
	^ LControl
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> LShift [
	"This method was automatically generated"
	^ LShift
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> LWin [
	"This method was automatically generated"
	^ LWin
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Left [
	"This method was automatically generated"
	^ Left
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> M [
	"This method was automatically generated"
	^ M
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Mail [
	"This method was automatically generated"
	^ Mail
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> MediaSelect [
	"This method was automatically generated"
	^ MediaSelect
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> MediaStop [
	"This method was automatically generated"
	^ MediaStop
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Minus [
	"This method was automatically generated"
	^ Minus
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Multiply [
	"This method was automatically generated"
	^ Multiply
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Mute [
	"This method was automatically generated"
	^ Mute
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> MyComputer [
	"This method was automatically generated"
	^ MyComputer
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> N [
	"This method was automatically generated"
	^ N
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NavigateBackward [
	"This method was automatically generated"
	^ NavigateBackward
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NavigateForward [
	"This method was automatically generated"
	^ NavigateForward
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NextTrack [
	"This method was automatically generated"
	^ NextTrack
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NoConvert [
	"This method was automatically generated"
	^ NoConvert
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numlock [
	"This method was automatically generated"
	^ Numlock
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad0 [
	"This method was automatically generated"
	^ Numpad0
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad1 [
	"This method was automatically generated"
	^ Numpad1
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad2 [
	"This method was automatically generated"
	^ Numpad2
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad3 [
	"This method was automatically generated"
	^ Numpad3
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad4 [
	"This method was automatically generated"
	^ Numpad4
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad5 [
	"This method was automatically generated"
	^ Numpad5
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad6 [
	"This method was automatically generated"
	^ Numpad6
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad7 [
	"This method was automatically generated"
	^ Numpad7
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad8 [
	"This method was automatically generated"
	^ Numpad8
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Numpad9 [
	"This method was automatically generated"
	^ Numpad9
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadAdd [
	"This method was automatically generated"
	^ NumpadAdd
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadComma [
	"This method was automatically generated"
	^ NumpadComma
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadDecimal [
	"This method was automatically generated"
	^ NumpadDecimal
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadDivide [
	"This method was automatically generated"
	^ NumpadDivide
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadEnter [
	"This method was automatically generated"
	^ NumpadEnter
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadEquals [
	"This method was automatically generated"
	^ NumpadEquals
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadMultiply [
	"This method was automatically generated"
	^ NumpadMultiply
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> NumpadSubtract [
	"This method was automatically generated"
	^ NumpadSubtract
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> O [
	"This method was automatically generated"
	^ O
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> OEM102 [
	"This method was automatically generated"
	^ OEM102
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> P [
	"This method was automatically generated"
	^ P
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> PageDown [
	"This method was automatically generated"
	^ PageDown
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> PageUp [
	"This method was automatically generated"
	^ PageUp
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Paste [
	"This method was automatically generated"
	^ Paste
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Pause [
	"This method was automatically generated"
	^ Pause
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Period [
	"This method was automatically generated"
	^ Period
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> PlayPause [
	"This method was automatically generated"
	^ PlayPause
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Plus [
	"This method was automatically generated"
	^ Plus
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Power [
	"This method was automatically generated"
	^ Power
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> PrevTrack [
	"This method was automatically generated"
	^ PrevTrack
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Q [
	"This method was automatically generated"
	^ Q
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> R [
	"This method was automatically generated"
	^ R
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> RAlt [
	"This method was automatically generated"
	^ RAlt
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> RBracket [
	"This method was automatically generated"
	^ RBracket
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> RControl [
	"This method was automatically generated"
	^ RControl
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> RShift [
	"This method was automatically generated"
	^ RShift
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> RWin [
	"This method was automatically generated"
	^ RWin
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Return [
	"This method was automatically generated"
	^ Return
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Right [
	"This method was automatically generated"
	^ Right
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> S [
	"This method was automatically generated"
	^ S
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Scroll [
	"This method was automatically generated"
	^ Scroll
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Semicolon [
	"This method was automatically generated"
	^ Semicolon
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Slash [
	"This method was automatically generated"
	^ Slash
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Sleep [
	"This method was automatically generated"
	^ Sleep
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Snapshot [
	"This method was automatically generated"
	^ Snapshot
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Space [
	"This method was automatically generated"
	^ Space
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Stop [
	"This method was automatically generated"
	^ Stop
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Subtract [
	"This method was automatically generated"
	^ Subtract
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Sysrq [
	"This method was automatically generated"
	^ Sysrq
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> T [
	"This method was automatically generated"
	^ T
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Tab [
	"This method was automatically generated"
	^ Tab
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> U [
	"This method was automatically generated"
	^ U
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Underline [
	"This method was automatically generated"
	^ Underline
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Unlabeled [
	"This method was automatically generated"
	^ Unlabeled
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Up [
	"This method was automatically generated"
	^ Up
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> V [
	"This method was automatically generated"
	^ V
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> VolumeDown [
	"This method was automatically generated"
	^ VolumeDown
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> VolumeUp [
	"This method was automatically generated"
	^ VolumeUp
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> W [
	"This method was automatically generated"
	^ W
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Wake [
	"This method was automatically generated"
	^ Wake
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebBack [
	"This method was automatically generated"
	^ WebBack
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebFavorites [
	"This method was automatically generated"
	^ WebFavorites
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebForward [
	"This method was automatically generated"
	^ WebForward
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebHome [
	"This method was automatically generated"
	^ WebHome
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebRefresh [
	"This method was automatically generated"
	^ WebRefresh
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebSearch [
	"This method was automatically generated"
	^ WebSearch
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> WebStop [
	"This method was automatically generated"
	^ WebStop
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> X [
	"This method was automatically generated"
	^ X
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Y [
	"This method was automatically generated"
	^ Y
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Yen [
	"This method was automatically generated"
	^ Yen
]

{ #category : #'accessing enum' }
WinitEventVirtualKeyCode class >> Z [
	"This method was automatically generated"
	^ Z
]

{ #category : #'enum declaration' }
WinitEventVirtualKeyCode class >> externalDeclaration [
	"
	self rebuildEnumAccessors
	"

	^ #(
		"The '1' key over the letters."
		Key1,
		"The '2' key over the letters."
		Key2,
		"The '3' key over the letters."
		Key3,
		"The '4' key over the letters."
		Key4,
		"The '5' key over the letters."
		Key5,
		"The '6' key over the letters."
		Key6,
		"The '7' key over the letters."
		Key7,
		"The '8' key over the letters."
		Key8,
		"The '9' key over the letters."
		Key9,
		"The '0' key over the 'O' and 'P' keys."
		Key0,

		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,

		"The Escape key, next to F1."
		Escape,

		F1,
		F2,
		F3,
		F4,
		F5,
		F6,
		F7,
		F8,
		F9,
		F10,
		F11,
		F12,
		F13,
		F14,
		F15,
		F16,
		F17,
		F18,
		F19,
		F20,
		F21,
		F22,
		F23,
		F24,

		"Print Screen/SysRq."
		Snapshot,
		"Scroll Lock."
		Scroll,
		"Pause/Break key, next to Scroll lock."
		Pause,


		Insert,
		Home,
		Delete,
		End,
		PageDown,
		PageUp,

		Left,
		Up,
		Right,
		Down,

		"The Backspace key, right over Enter."
		Back,
		"The Enter key."
		Return,
		"The space bar."
		Space,

		"The Compose key on Linux."
		Compose,

		Caret,

		Numlock,
		Numpad0,
		Numpad1,
		Numpad2,
		Numpad3,
		Numpad4,
		Numpad5,
		Numpad6,
		Numpad7,
		Numpad8,
		Numpad9,
		NumpadAdd,
		NumpadDivide,
		NumpadDecimal,
		NumpadComma,
		NumpadEnter,
		NumpadEquals,
		NumpadMultiply,
		NumpadSubtract,

		AbntC1,
		AbntC2,
		Apostrophe,
		Apps,
		Asterisk,
		At,
		Ax,
		Backslash,
		Calculator,
		Capital,
		Colon,
		Comma,
		Convert,
		Equals,
		Grave,
		Kana,
		Kanji,
		LAlt,
		LBracket,
		LControl,
		LShift,
		LWin,
		Mail,
		MediaSelect,
		MediaStop,
		Minus,
		Mute,
		MyComputer,
		"also called Next"
		NavigateForward,
		"also called Prior"
		NavigateBackward,
		NextTrack,
		NoConvert,
		OEM102,
		Period,
		PlayPause,
		Plus,
		Power,
		PrevTrack,
		RAlt,
		RBracket,
		RControl,
		RShift,
		RWin,
		Semicolon,
		Slash,
		Sleep,
		Stop,
		Sysrq,
		Tab,
		Underline,
		Unlabeled,
		VolumeDown,
		VolumeUp,
		Wake,
		WebBack,
		WebFavorites,
		WebForward,
		WebHome,
		WebRefresh,
		WebSearch,
		WebStop,
		Yen,
		Copy,
		Paste,
		Cut,
	)
]

{ #category : #'enum declaration' }
WinitEventVirtualKeyCode class >> externalType [
	^ FFIUInt32 new
]

{ #category : #'class initialization' }
WinitEventVirtualKeyCode class >> initialize [
	super initialize
]
