Trait {
	#name : #TWinitEventVisitor,
	#category : #'Winit-Events'
}

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitCharacterReceivedEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitCursorEnteredEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitCursorLeftEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitCursorMovedEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitKeyboardInputEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitLoopDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitMainEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitModifiersChanged: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitMouseInputEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitMouseWheelEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitNewEvents: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitRedrawEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitResumed: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitSuspended: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitTouchEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitUnknownEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitUserEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowCloseRequest: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowFocusedEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowMovedEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowRedrawRequested: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowResizedEvent: anEvent [
]

{ #category : #'event - visiting' }
TWinitEventVisitor >> visitWindowScaleFactorChangedEvent: anEvent [
]
