Trait {
	#name : #TWinitCommonEventVisitor,
	#category : #'Winit-Events'
}

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitLoopDestroyed: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitMainEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitNewEvents: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitRedrawEventsCleared: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitResumed: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitSuspended: anEvent [
]

{ #category : #'event - visiting' }
TWinitCommonEventVisitor >> visitUserEvent: anEvent [
]
